# Generated by Django 6.0.4 on 2026-04-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide', models.CharField(choices=[('mamans', 'Mamans'), ('sages_femmes', 'Sages-Femmes'), ('pharmaciens', 'Pharmaciens')], max_length=20)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('date_entretien', models.CharField(blank=True, max_length=20)),
                ('profil', models.CharField(blank=True, max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('score_motivation', models.IntegerField(blank=True, null=True)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('reponses', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
